-- Create the table
create table places (
  id bigint generated by default as identity primary key,
  name text not null,
  type text not null check (type in ('FISHING', 'CAMPING')),
  address text,
  lat double precision,
  lng double precision,
  "desc" text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security (RLS)
alter table places enable row level security;

-- Create a policy that allows anyone to read data
create policy "Allow public read access"
  on places for select
  using ( true );

-- Create a policy that allows authenticated users to insert data (optional, for future use)
-- create policy "Allow authenticated insert access"
--   on places for insert
--   with check ( auth.role() = 'authenticated' );
